# PRhythm Configuration Example

# General settings
general:
  timezone: "Asia/Shanghai"    # Timezone for date/time operations

# GitHub repositories to monitor
github:
  repositories:
    - owner/repo1
    - owner/repo2
  check_interval: 3600  # in seconds (1 hour)
  # GitHub token for authentication
  # Option 1: Set directly here (not recommended for production)
  # token: "your-github-token-here"
  # Option 2: Set via environment variable (recommended)
  token: ""  # Will use GITHUB_TOKEN environment variable if empty
  # Optional: filter PRs by labels
  # include_labels:
  #   - feature
  #   - bugfix
  # exclude_labels:
  #   - wip
  #   - do-not-merge

# LLM API configuration
llm:
  # Default provider configuration
  provider: "openai"  # or "anthropic", "deepseek", etc.
  # Option 1: Set API key directly here (not recommended for production)
  # api_key: "your-llm-api-key-here"
  # Option 2: Set via environment variable (recommended)
  api_key: ""  # Will use LLM_API_KEY environment variable if empty
  model: "gpt-4"  # or "claude-3-opus", etc.
  temperature: 0.3
  
  # Provider-specific configurations
  providers:
    openai:
      base_url: "https://api.openai.com/v1"
      # model and api_key will be inherited from the default settings if not specified
    
    deepseek:
      base_url: "https://api.deepseek.com"
      # Option 1: Set API key directly here (not recommended for production)
      # api_key: "your-deepseek-api-key-here"
      # Option 2: Set via environment variable (recommended)
      api_key: ""  # Will use DEEPSEEK_API_KEY environment variable if empty
      model: "deepseek-chat"  # Available models: deepseek-chat (DeepSeek-V3), deepseek-reasoner (DeepSeek-R1)
  
# Output configuration
output:
  # Primary language for analysis reports: "en" (English), "zh-cn" (Chinese), etc.
  primary_language: "en"
  
  # Enable multilingual output
  multilingual: false
  
  # Languages to generate reports in (when multilingual is true)
  languages:
    - "en"     # English
    - "zh-cn"  # Chinese (Simplified)
    # - "ja"     # Japanese
    # - "ko"     # Korean
    # Uncomment or add more languages as needed
  
  # Additional output formatting options can be added here

# Viewer configuration
viewer:
  enabled: true                # Enable or disable the Markdown viewer
  port: 8080                   # Port to use for the Markdown viewer
  debug: false                 # Enable debug mode for the Flask application
  analysis_dir: "./analysis"   # Directory where analysis reports are stored 