services:
  prhythm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: prhythm
    volumes:
      - ..:/app  # Map the entire project directory to the container
      - ~/Workspace/unknownue.github.io/content/pull_request:/app/analysis
      - ~/.config/gh:/root/.config/gh:ro  # Mount GitHub CLI credentials (read-only)
    restart: unless-stopped
    ports:
      - "${VIEWER_PORT:-9090}:${VIEWER_PORT:-9090}"  # Expose port for the Markdown viewer (default to 9090)
    environment:
      - TZ=${TZ:-UTC}
      - PYTHONUNBUFFERED=1  # Disable Python output buffering to ensure real-time logging
      # Pass environment variables from shell to container
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - LLM_API_KEY=${LLM_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - VIEWER_PORT=${VIEWER_PORT:-9090}  # Set the viewer port (default to 9090)
      # - NOTION_API_KEY=${NOTION_API_KEY}
    # Use entrypoint script to start the service
    command: /app/docker/entrypoint.sh
    # Uncomment below to use custom command instead
    # command: python pipeline/analyze_pr.py --json output/repo/pr_123_20240228_123456.json --language zh-cn 